// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

/*~ Input Tags ~*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Crouch);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Aim);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Input_Fire);

/*~ Equipment Tags ~*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Equipment);

/*~ Character States ~*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Sprint);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Crouch);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Aiming);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Weapon_CannotFire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Weapon_Crosshair);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_State_Weapon_Crosshair_Rifle);

/*~ SetByCaller Tags - Weapon Attributes ~*/
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_Ammo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_MaxAmmo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_ReserveAmmo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_MaxReserveAmmo);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_FireRate);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_ReloadTime);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_BaseDamage);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_DamageMultiplier);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_Energy);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_MaxEnergy);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_EnergyDrainRate);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_LoadedMissiles);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_MaxLoadedMissiles);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_SetByCaller_Weapon_ExplosionRadius);
